Tag.find_or_create_by(name: "Sidhu Moosewala")
Tag.find_or_create_by(name: "Karan Aujla")
Tag.find_or_create_by(name: "Gurdass Maan")
Tag.find_or_create_by(name: "Jordan Sandhu")
Tag.find_or_create_by(name: "Punjabi Singers")
Tag.find_or_create_by(name: "Punjabi")
Tag.find_or_create_by(name: "Beats")
Tag.find_or_create_by(name: "Singer")
